// <auto-generated />
using System;
using BPRadar.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BPRadar.Web.Data.Migrations
{
    [DbContext(typeof(BPRadarDbContext))]
    [Migration("20260813075753_AssessmentLifecycle")]
    partial class AssessmentLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BPRadar.Web.Data.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaselineProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrameworkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaselineProfileId");

                    b.HasIndex("FrameworkId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("BPRadar.Web.Data.AssessmentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ControlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("AssessmentId", "ControlId")
                        .IsUnique();

                    b.ToTable("AssessmentResults");
                });

            modelBuilder.Entity("BPRadar.Web.Data.BaselineProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("BaselineProfiles");
                });

            modelBuilder.Entity("BPRadar.Web.Data.BaselineTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaselineProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DomainId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrameworkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetCompliancePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("FrameworkId");

                    b.HasIndex("BaselineProfileId", "FrameworkId")
                        .IsUnique()
                        .HasFilter("\"DomainId\" IS NULL");

                    b.HasIndex("BaselineProfileId", "FrameworkId", "DomainId")
                        .IsUnique()
                        .HasFilter("\"DomainId\" IS NOT NULL");

                    b.ToTable("BaselineTargets");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Control", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DomainId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuidanceUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainId", "Code")
                        .IsUnique();

                    b.ToTable("Controls");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("FrameworkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkId", "Code")
                        .IsUnique();

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Framework", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("Frameworks");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchingError")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootCause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("BPRadar.Web.Data.SurveyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ControlId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DomainId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrameworkId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurveyTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("DomainId");

                    b.HasIndex("FrameworkId");

                    b.HasIndex("SurveyTemplateId", "Code")
                        .IsUnique();

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("BPRadar.Web.Data.SurveyResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Score")
                        .HasColumnType("TEXT");

                    b.Property<int>("SurveyQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurveySubmissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionId");

                    b.HasIndex("SurveySubmissionId", "SurveyQuestionId")
                        .IsUnique();

                    b.ToTable("SurveyResponses");
                });

            modelBuilder.Entity("BPRadar.Web.Data.SurveySubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SurveyTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SurveyTemplateId");

                    b.HasIndex("OrganizationId", "SurveyTemplateId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("SurveySubmissions");
                });

            modelBuilder.Entity("BPRadar.Web.Data.SurveyTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrameworkId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SurveyTemplates");
                });

            modelBuilder.Entity("BPRadar.Web.Data.ViolationMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ControlId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelfAssessmentDiscrepancy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MatchScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("IssueId", "ControlId")
                        .IsUnique();

                    b.ToTable("ViolationMatches");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Assessment", b =>
                {
                    b.HasOne("BPRadar.Web.Data.BaselineProfile", "BaselineProfile")
                        .WithMany()
                        .HasForeignKey("BaselineProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BPRadar.Web.Data.Framework", "Framework")
                        .WithMany()
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BPRadar.Web.Data.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaselineProfile");

                    b.Navigation("Framework");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BPRadar.Web.Data.AssessmentResult", b =>
                {
                    b.HasOne("BPRadar.Web.Data.Assessment", "Assessment")
                        .WithMany("Results")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BPRadar.Web.Data.Control", "Control")
                        .WithMany()
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Control");
                });

            modelBuilder.Entity("BPRadar.Web.Data.BaselineProfile", b =>
                {
                    b.HasOne("BPRadar.Web.Data.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BPRadar.Web.Data.BaselineTarget", b =>
                {
                    b.HasOne("BPRadar.Web.Data.BaselineProfile", "BaselineProfile")
                        .WithMany("Targets")
                        .HasForeignKey("BaselineProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BPRadar.Web.Data.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BPRadar.Web.Data.Framework", "Framework")
                        .WithMany()
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaselineProfile");

                    b.Navigation("Domain");

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Control", b =>
                {
                    b.HasOne("BPRadar.Web.Data.Domain", "Domain")
                        .WithMany("Controls")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Domain", b =>
                {
                    b.HasOne("BPRadar.Web.Data.Framework", "Framework")
                        .WithMany("Domains")
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Issue", b =>
                {
                    b.HasOne("BPRadar.Web.Data.Organization", "Organization")
                        .WithMany("Issues")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BPRadar.Web.Data.SurveyQuestion", b =>
                {
                    b.HasOne("BPRadar.Web.Data.Control", "Control")
                        .WithMany()
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BPRadar.Web.Data.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BPRadar.Web.Data.Framework", "Framework")
                        .WithMany()
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BPRadar.Web.Data.SurveyTemplate", "SurveyTemplate")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Control");

                    b.Navigation("Domain");

                    b.Navigation("Framework");

                    b.Navigation("SurveyTemplate");
                });

            modelBuilder.Entity("BPRadar.Web.Data.SurveyResponse", b =>
                {
                    b.HasOne("BPRadar.Web.Data.SurveyQuestion", "SurveyQuestion")
                        .WithMany()
                        .HasForeignKey("SurveyQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BPRadar.Web.Data.SurveySubmission", "SurveySubmission")
                        .WithMany("Responses")
                        .HasForeignKey("SurveySubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyQuestion");

                    b.Navigation("SurveySubmission");
                });

            modelBuilder.Entity("BPRadar.Web.Data.SurveySubmission", b =>
                {
                    b.HasOne("BPRadar.Web.Data.Organization", "Organization")
                        .WithMany("SurveySubmissions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BPRadar.Web.Data.SurveyTemplate", "SurveyTemplate")
                        .WithMany()
                        .HasForeignKey("SurveyTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("SurveyTemplate");
                });

            modelBuilder.Entity("BPRadar.Web.Data.SurveyTemplate", b =>
                {
                    b.HasOne("BPRadar.Web.Data.Framework", "Framework")
                        .WithMany()
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("BPRadar.Web.Data.ViolationMatch", b =>
                {
                    b.HasOne("BPRadar.Web.Data.Control", "Control")
                        .WithMany()
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BPRadar.Web.Data.Issue", "Issue")
                        .WithMany("ViolationMatches")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Control");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Assessment", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("BPRadar.Web.Data.BaselineProfile", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Domain", b =>
                {
                    b.Navigation("Controls");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Framework", b =>
                {
                    b.Navigation("Domains");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Issue", b =>
                {
                    b.Navigation("ViolationMatches");
                });

            modelBuilder.Entity("BPRadar.Web.Data.Organization", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("SurveySubmissions");
                });

            modelBuilder.Entity("BPRadar.Web.Data.SurveySubmission", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("BPRadar.Web.Data.SurveyTemplate", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
